### ISSUE TITLE
Error in version 1.8.2 but 1.8.1 works fine

### ISSUE THREAD

**Issue by irriss** [Azure/azure-documentdb-datamigrationtool#93] opened 2019-04-11 02:37 UTC
Hello everyone!

Seems there is an issue with the latest version 1.8.2

When I try to import data from one partitioned Cosmos Db collection to another one I face this issue for every record:

```
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Documents.Client.ResourceResponse`1<Microsoft.Azure.Documents.Document>> Microsoft.Azure.Documents.Client.DocumentClient.CreateDocumentAsync(System.String, System.Object, Microsoft.Azure.Documents.Client.RequestOptions, Boolean)'.    at Microsoft.Azure.Documents.Client.TransientFaultHandling.Implementation.ReliableReadWriteDocumentClient.<>c__DisplayClass1c.<CreateDocumentAsync>b__1b()    at Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling.AsyncExecution`1.ExecuteAsyncImpl(Task ignore)    at Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling.RetryPolicy.ExecuteAsync[TResult](Func`1 taskFunc, CancellationToken cancellationToken)    at Microsoft.Azure.Documents.Client.TransientFaultHandling.Implementation.ReliableReadWriteDocumentClient.CreateDocumentAsync(String collectionLink, Object document, RequestOptions options, Boolean disableAutomaticIdGeneration)    at Microsoft.DataTransfer.DocumentDb.Client.DocumentDbClient.CreateDocumentAsync(String collectionLink, Object document, Boolean disableAutomaticIdGeneration) in d:\a\1\s\DocumentDb\Microsoft.DataTransfer.DocumentDb\Client\DocumentDbClient.cs:line 98    at Microsoft.DataTransfer.DocumentDb.Sink.Parallel.DocumentDbParallelSinkAdapter.WriteAsync(IDataItem dataItem, CancellationToken cancellation) in d:\a\1\s\DocumentDb\Microsoft.DataTransfer.DocumentDb\Sink\Parallel\DocumentDbParallelSinkAdapter.cs:line 39    at Microsoft.DataTransfer.Core.Service.DataTransferAction.<TransferDataItem>d__1.MoveNext() in d:\a\1\s\Core\Microsoft.DataTransfer.Core\Service\DataTransferAction.cs:line 79
```

The data extraction goes well (I tried exporting to JSON) so the issue is with creating records at target database.

I tried different settings but could solve it.

However, version 1.8.1 works fine.

Looks like some incompatibility but with what exactly?

Thanks, the tool makes life much easier.

**Comment by iMicknl** [comment] 2019-04-22 18:55
+1. Can reproduce the same issue using the master branch. It looks like the DocumentDB client got updated from `1.x` to `2.x`, which could cause this kind of issues.

**Comment by haitsongmsft** [comment] 2019-05-02 18:17
It should be fixed now in the main

**Closed as completed by haitsongmsft** 2019-05-02 18:17 UTC

**Comment by iMicknl** [comment] 2019-05-22 18:53
@haitsongmsft latest commit in `master` is still dating from April 6. Did you push your code? ;-)
And would it be possible to release 1.8.2 and tag the release? (https://github.com/Azure/azure-documentdb-datamigrationtool/releases)
